"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { BrowserMultiFormatOneDReader, type IScannerControls } from "@zxing/browser";
import { BarcodeFormat, DecodeHintType } from "@zxing/library";
import * as bwipjs from "bwip-js";

type StoreType=string;
type Product={id:number;name:string;price:number;category:string;icon:string;unit:string;barcode:string;color:string;image?:string;storeType?:StoreType;stock?:number};
type CustomStore={type:string;icon:string;description:string};
type ExtendedTrackConstraints=MediaTrackConstraints&{focusMode?:"continuous";exposureMode?:"continuous"};
type CartItem=Product&{quantity:number;basePrice?:number;baseUnit?:string;measured?:boolean};
type Receipt={id:string;barcode:string;items:CartItem[];total:number;tax:number;payment:"Bar"|"Karte"|"Rückgabe";given?:number;change?:number;date:string;createdAt:number;number:string;kind:"sale"|"return";storeType:StoreType;originalNumber?:string;note?:string};
type Settings={storeName:string;logo:string};
type Coupon={id:number;code:string;label:string;amount:number;active:boolean};
type NativeBarcodeDetector={detect:(source:HTMLVideoElement|HTMLCanvasElement)=>Promise<Array<{rawValue:string}>>};
type NativeBarcodeDetectorConstructor=new(options?:{formats?:string[]})=>NativeBarcodeDetector;

const defaultProducts:Product[]=[
  {id:1,name:"Vollmilch",price:1.49,category:"Kühlregal",icon:"🥛",unit:"1 L",barcode:"400001",color:"#e9f4ff",image:"https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=500&q=80"},{id:2,name:"Naturjoghurt",price:1.29,category:"Kühlregal",icon:"🥣",unit:"500 g",barcode:"400002",color:"#f2ecff",image:"https://images.unsplash.com/photo-1571212515416-fca77afa0b1f?auto=format&fit=crop&w=500&q=80"},{id:3,name:"Gouda Käse",price:2.79,category:"Kühlregal",icon:"🧀",unit:"250 g",barcode:"400003",color:"#fff3cf",image:"https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=500&q=80"},{id:4,name:"Butter",price:2.19,category:"Kühlregal",icon:"🧈",unit:"250 g",barcode:"400004",color:"#fff8d8",image:"https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=500&q=80"},
  {id:5,name:"Äpfel",price:2.49,category:"Obst & Gemüse",icon:"🍎",unit:"1 kg",barcode:"400005",color:"#ffe7e5",image:"https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=500&q=80"},{id:6,name:"Bananen",price:1.69,category:"Obst & Gemüse",icon:"🍌",unit:"1 kg",barcode:"400006",color:"#fff6c9",image:"https://images.unsplash.com/photo-1603833665858-e61d17a86224?auto=format&fit=crop&w=500&q=80"},{id:7,name:"Tomaten",price:2.99,category:"Obst & Gemüse",icon:"🍅",unit:"500 g",barcode:"400007",color:"#ffe3df",image:"https://images.unsplash.com/photo-1561136594-7f68413baa99?auto=format&fit=crop&w=500&q=80"},{id:8,name:"Gurke",price:.99,category:"Obst & Gemüse",icon:"🥒",unit:"Stück",barcode:"400008",color:"#e2f6df",image:"https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?auto=format&fit=crop&w=500&q=80"},
  {id:9,name:"Bauernbrot",price:2.89,category:"Backwaren",icon:"🍞",unit:"750 g",barcode:"400009",color:"#f7e7d2",image:"https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=500&q=80"},{id:10,name:"Croissant",price:.89,category:"Backwaren",icon:"🥐",unit:"Stück",barcode:"400010",color:"#fff0d7",image:"https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=500&q=80"},{id:11,name:"Mineralwasser",price:.79,category:"Getränke",icon:"💧",unit:"1,5 L",barcode:"400011",color:"#e1f5ff",image:"https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=500&q=80"},{id:12,name:"Orangensaft",price:2.39,category:"Getränke",icon:"🍊",unit:"1 L",barcode:"400012",color:"#ffecd2",image:"https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=500&q=80"},{id:13,name:"Cola",price:1.49,category:"Getränke",icon:"🥤",unit:"1 L",barcode:"400013",color:"#eee7e3",image:"https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=500&q=80"},{id:14,name:"Nudeln",price:1.19,category:"Vorrat",icon:"🍝",unit:"500 g",barcode:"400014",color:"#fff0c7",image:"https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?auto=format&fit=crop&w=500&q=80"},{id:15,name:"Reis",price:2.59,category:"Vorrat",icon:"🍚",unit:"1 kg",barcode:"400015",color:"#f4f0e8",image:"https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80"},{id:16,name:"Schokolade",price:1.39,category:"Süßes",icon:"🍫",unit:"100 g",barcode:"400016",color:"#eee1db",image:"https://images.unsplash.com/photo-1575377427642-087cf684f29d?auto=format&fit=crop&w=500&q=80"}
];
const shopProducts:Product[]=[
  {id:101,name:"Super E10",price:1.79,category:"Kraftstoff",icon:"⛽",unit:"Liter",barcode:"510001",color:"#e8f1eb",storeType:"Tanke",image:"https://images.unsplash.com/photo-1527018601619-a508a2be00cd?auto=format&fit=crop&w=500&q=80"},
  {id:102,name:"Diesel",price:1.69,category:"Kraftstoff",icon:"⛽",unit:"Liter",barcode:"510002",color:"#ece9df",storeType:"Tanke",image:"https://images.unsplash.com/photo-1545262810-77515befe149?auto=format&fit=crop&w=500&q=80"},
  {id:103,name:"Motoröl 5W-30",price:14.99,category:"Autozubehör",icon:"🛢️",unit:"1 L",barcode:"510003",color:"#ececec",storeType:"Tanke",image:"https://images.unsplash.com/photo-1635773054018-71c7234fe753?auto=format&fit=crop&w=500&q=80"},
  {id:104,name:"Premium Autowäsche",price:12.99,category:"Waschanlage",icon:"🚿",unit:"Programm",barcode:"510004",color:"#e4f4fa",storeType:"Tanke",image:"https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&w=500&q=80"},
  {id:201,name:"Bausteine-Set",price:29.99,category:"Bauen",icon:"🧱",unit:"Set",barcode:"520001",color:"#fff2d7",storeType:"Spielzeugladen",image:"https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=500&q=80"},
  {id:202,name:"Teddybär",price:18.99,category:"Plüschtiere",icon:"🧸",unit:"Stück",barcode:"520002",color:"#f7e8dc",storeType:"Spielzeugladen",image:"https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=500&q=80"},
  {id:203,name:"Ferngesteuertes Auto",price:39.99,category:"Fahrzeuge",icon:"🏎️",unit:"Stück",barcode:"520003",color:"#e5eef7",storeType:"Spielzeugladen",image:"https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=500&q=80"},
  {id:204,name:"Puzzle 1000 Teile",price:13.49,category:"Spiele",icon:"🧩",unit:"Stück",barcode:"520004",color:"#f0e9fa",storeType:"Spielzeugladen",image:"https://images.unsplash.com/photo-1611996575749-79a3a250f948?auto=format&fit=crop&w=500&q=80"},
  {id:301,name:"Bargeldabhebung",price:100,category:"Bankservice",icon:"💶",unit:"Vorgang",barcode:"530001",color:"#e9f5ed",storeType:"Bank",image:"https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=500&q=80"},
  {id:302,name:"Überweisung",price:2.5,category:"Bankservice",icon:"↗️",unit:"Gebühr",barcode:"530002",color:"#e8eef8",storeType:"Bank",image:"https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=500&q=80"},
  {id:303,name:"Kontoeröffnung",price:9.99,category:"Bankservice",icon:"🏦",unit:"Service",barcode:"530003",color:"#eceff2",storeType:"Bank",image:"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=500&q=80"},
  {id:304,name:"Schließfach",price:79,category:"Bankservice",icon:"🔐",unit:"Jahr",barcode:"530004",color:"#f1eadf",storeType:"Bank",image:"https://images.unsplash.com/photo-1565514020179-026b92b84bb6?auto=format&fit=crop&w=500&q=80"},
  {id:401,name:"Wohnsofa",price:799,category:"Wohnzimmer",icon:"🛋️",unit:"Stück",barcode:"540001",color:"#eee8e1",storeType:"Möbelladen",image:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=500&q=80"},
  {id:402,name:"Esstisch",price:449,category:"Esszimmer",icon:"🪵",unit:"Stück",barcode:"540002",color:"#efe6dc",storeType:"Möbelladen",image:"https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?auto=format&fit=crop&w=500&q=80"},
  {id:403,name:"Esszimmerstuhl",price:129,category:"Esszimmer",icon:"🪑",unit:"Stück",barcode:"540003",color:"#eee9e2",storeType:"Möbelladen",image:"https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=500&q=80"},
  {id:404,name:"Stehlampe",price:89.99,category:"Beleuchtung",icon:"💡",unit:"Stück",barcode:"540004",color:"#fff3d7",storeType:"Möbelladen",image:"https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=500&q=80"},
  {id:501,name:"Kompaktwagen",price:21990,category:"Autos",icon:"🚗",unit:"Fahrzeug",barcode:"550001",color:"#e7edf2",storeType:"Fahrzeugladen",image:"https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=500&q=80"},
  {id:502,name:"SUV",price:38990,category:"Autos",icon:"🚙",unit:"Fahrzeug",barcode:"550002",color:"#e8ecef",storeType:"Fahrzeugladen",image:"https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=500&q=80"},
  {id:503,name:"Motorrad",price:12990,category:"Motorräder",icon:"🏍️",unit:"Fahrzeug",barcode:"550003",color:"#ece8e8",storeType:"Fahrzeugladen",image:"https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=500&q=80"},
  {id:504,name:"E-Bike",price:2899,category:"Fahrräder",icon:"🚲",unit:"Fahrzeug",barcode:"550004",color:"#e6f0eb",storeType:"Fahrzeugladen",image:"https://images.unsplash.com/photo-1571068316344-75bc76f77890?auto=format&fit=crop&w=500&q=80"},
];
const storeOptions:{type:StoreType;icon:string;description:string}[]=[
  {type:"Tanke",icon:"⛽",description:"Kraftstoff, Autowäsche und Zubehör"},{type:"Supermarkt",icon:"🛒",description:"Lebensmittel, Getränke und Haushalt"},{type:"Spielzeugladen",icon:"🧸",description:"Spiele, Bausteine und Spielzeug"},{type:"Bank",icon:"🏦",description:"Bankgeschäfte und Services"},{type:"Möbelladen",icon:"🛋️",description:"Möbel und Einrichtung"},{type:"Fahrzeugladen",icon:"🚗",description:"Autos, Motorräder und Fahrräder"},{type:"Alle",icon:"▦",description:"Alle Läden und alle Produkte"},
];
type CommonsImageResponse={query?:{pages?:Record<string,{imageinfo?:Array<{thumburl?:string;url?:string}>}>}};
const catalogProducts=[...defaultProducts,...shopProducts];
async function findProductImageByName(name:string,category:string){
  const normalized=name.toLocaleLowerCase("de-DE");
  const catalogMatch=catalogProducts.find(product=>normalized.includes(product.name.toLocaleLowerCase("de-DE"))||product.name.toLocaleLowerCase("de-DE").includes(normalized));
  if(catalogMatch?.image)return catalogMatch.image;
  try{
    const query=`${name} ${category} Produkt`;
    const url=`https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrnamespace=6&gsrlimit=8&gsrsearch=${encodeURIComponent(query)}&prop=imageinfo&iiprop=url&iiurlwidth=700&format=json&origin=*`;
    const response=await fetch(url);
    if(!response.ok)return "";
    const data=await response.json() as CommonsImageResponse;
    return Object.values(data.query?.pages||{}).map(page=>page.imageinfo?.[0]?.thumburl||page.imageinfo?.[0]?.url||"").find(Boolean)||"";
  }catch{return ""}
}
const money=(v:number)=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(v);
const measureData=(unit:string)=>{const match=unit.trim().match(/^(\d+(?:[,.]\d+)?)\s*(kg|g|ml|l|liter|mm|cm|m)$/i);if(!match)return null;const amount=Number(match[1].replace(",",".")),name=match[2].toLowerCase();const factors:Record<string,number>={g:1,kg:1000,ml:1,l:1000,liter:1000,mm:1,cm:10,m:1000};const group=name==="g"||name==="kg"?"weight":name==="ml"||name==="l"||name==="liter"?"volume":"length";return{amount,unit:name==="liter"?"L":name,factor:factors[name],group}};
const measureUnits=(group?:string)=>group==="weight"?["g","kg"]:group==="volume"?["ml","L"]:group==="length"?["mm","cm","m"]:[];
const barcodeCandidates=(video:HTMLVideoElement)=>{const source=document.createElement("canvas");source.width=video.videoWidth;source.height=video.videoHeight;const sourceCtx=source.getContext("2d");if(!sourceCtx)return[];sourceCtx.drawImage(video,0,0);const crop=document.createElement("canvas"),sw=Math.round(source.width*.88),sh=Math.round(source.height*.58);crop.width=Math.max(1,sw);crop.height=Math.max(1,sh);crop.getContext("2d")?.drawImage(source,(source.width-sw)/2,(source.height-sh)/2,sw,sh,0,0,sw,sh);const enhanced=document.createElement("canvas");enhanced.width=crop.width;enhanced.height=crop.height;const enhancedCtx=enhanced.getContext("2d");if(enhancedCtx){enhancedCtx.filter="grayscale(1) contrast(2.5) brightness(1.08)";enhancedCtx.drawImage(crop,0,0)}const results=[source,crop,enhanced];for(const angle of[-12,-7,7,12]){const rotated=document.createElement("canvas");rotated.width=enhanced.width;rotated.height=enhanced.height;const ctx=rotated.getContext("2d");if(!ctx)continue;ctx.fillStyle="#fff";ctx.fillRect(0,0,rotated.width,rotated.height);ctx.translate(rotated.width/2,rotated.height/2);ctx.rotate(angle*Math.PI/180);ctx.drawImage(enhanced,-enhanced.width/2,-enhanced.height/2);results.push(rotated)}return results};

function ReceiptBarcode({value}:{value:string}){
  const canvasRef=useRef<HTMLCanvasElement|null>(null);
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;try{bwipjs.toCanvas(canvas,{bcid:"code128",text:value,scale:2,height:12,includetext:false,paddingwidth:0,paddingheight:0})}catch{}},[value]);
  return <div className="receipt-barcode"><canvas ref={canvasRef}/><small>{value}</small></div>;
}

function ReceiptPaper({receipt,settings,className=""}:{receipt:Receipt;settings:Settings;className?:string}){
  return <article className={`receipt-paper ${className}`}>
    <header>{settings.logo?<img src={settings.logo} alt="Ladenlogo"/>:<h2>{settings.storeName||"MEIN LADEN"}</h2>}<p>{receipt.kind==="return"?"RÜCKGABEBON":"KASSENBON"}</p></header>
    <div className="receipt-meta"><span>{receipt.date}</span><span>Bon {receipt.number}</span></div><div className="receipt-rule"/>
    <div className="receipt-lines">{receipt.items.map(item=><div key={item.id}><span>{item.quantity} × {item.name}<small>{money(item.price)} / {item.unit}</small></span><b>{money(item.price*item.quantity)}</b></div>)}</div>
    <div className="receipt-rule"/><div className="receipt-sum"><p><span>SUMME</span><strong>{money(receipt.total)}</strong></p><p><span>Enthaltene MwSt. 19 %</span><span>{money(receipt.tax)}</span></p><p><span>Zahlung</span><span>{receipt.payment}</span></p>{receipt.originalNumber&&<p><span>Originalbon</span><span>{receipt.originalNumber}</span></p>}{receipt.payment==="Bar"&&<><p><span>Gegeben</span><span>{money(receipt.given||0)}</span></p><p><span>Rückgeld</span><strong>{money(receipt.change||0)}</strong></p></>}</div>
    {receipt.note&&<><div className="receipt-rule"/><p className="receipt-note">Notiz: {receipt.note}</p></>}<div className="receipt-rule"/><ReceiptBarcode value={receipt.barcode}/><footer>{receipt.kind==="return"?"Rückgabe erfolgreich verbucht.":"Vielen Dank für Ihren Einkauf!"}<small>Barcode scannen, um diesen Bon digital zu öffnen.</small></footer>
  </article>
}

export default function Home(){
  const [loggedIn,setLoggedIn]=useState(false),[loginError,setLoginError]=useState(""),[username,setUsername]=useState(""),[password,setPassword]=useState("");
  const [storeType,setStoreType]=useState<StoreType|null>(null);
  const [customProducts,setCustomProducts]=useState<Product[]>([]),[settings,setSettings]=useState<Settings>({storeName:"Mein Supermarkt",logo:""}),[hydrated,setHydrated]=useState(false);
  const [cart,setCart]=useState<CartItem[]>([]),[category,setCategory]=useState("Alle"),[search,setSearch]=useState(""),[barcode,setBarcode]=useState(""),[notice,setNotice]=useState("Kasse bereit");
  const [payment,setPayment]=useState<null|"cash"|"card">(null),[paymentAmount,setPaymentAmount]=useState(""),[cash,setCash]=useState(""),[paymentCouponCode,setPaymentCouponCode]=useState(""),[paymentCoupon,setPaymentCoupon]=useState<Coupon|null>(null),[paymentCouponError,setPaymentCouponError]=useState(""),[receipt,setReceipt]=useState<Receipt|null>(null),[sales,setSales]=useState(0),[transactions,setTransactions]=useState(0),[clock,setClock]=useState("--:--");
  const [showProduct,setShowProduct]=useState(false),[productError,setProductError]=useState(""),[autoImageLoading,setAutoImageLoading]=useState(false),[showSettings,setShowSettings]=useState(false),[logoDraft,setLogoDraft]=useState(""),[storeDraft,setStoreDraft]=useState("Mein Supermarkt");
  const [receiptHistory,setReceiptHistory]=useState<Receipt[]>([]),[showHistory,setShowHistory]=useState(false),[editingReceipt,setEditingReceipt]=useState<Receipt|null>(null);
  const [showPrintManager,setShowPrintManager]=useState(false),[printSelection,setPrintSelection]=useState<string[]>([]);
  const [priceOverrides,setPriceOverrides]=useState<Record<string,number>>({}),[editingProduct,setEditingProduct]=useState<Product|null>(null),[editPrice,setEditPrice]=useState("");
  const [coupons,setCoupons]=useState<Coupon[]>([]),[showCoupons,setShowCoupons]=useState(false),[couponError,setCouponError]=useState(""),[couponDraft,setCouponDraft]=useState({code:"",label:"Angebot",amount:""});
  const [measuringItem,setMeasuringItem]=useState<CartItem|null>(null),[measureAmount,setMeasureAmount]=useState(""),[measureUnit,setMeasureUnit]=useState("");
  const [newProduct,setNewProduct]=useState({name:"",price:"",amount:"1",measure:"Stück",category:"Eigene Artikel",barcode:"",icon:"📦",image:"",stock:"25"});
  const [scannerMode,setScannerMode]=useState<null|"checkout"|"mde"|"new"|"coupon">(null),[scannerError,setScannerError]=useState(""),[scanSnapStatus,setScanSnapStatus]=useState("");
  const [stocks,setStocks]=useState<Record<string,number>>({}),[mdeProduct,setMdeProduct]=useState<Product|null>(null),[customStores,setCustomStores]=useState<CustomStore[]>([]);
  const [showPhotoCamera,setShowPhotoCamera]=useState(false),[photoCameraError,setPhotoCameraError]=useState("");
  const videoRef=useRef<HTMLVideoElement|null>(null),scannerControlsRef=useRef<IScannerControls|null>(null),scanLockRef=useRef(false);
  const productVideoRef=useRef<HTMLVideoElement|null>(null),productStreamRef=useRef<MediaStream|null>(null);

  useEffect(()=>{try{setCustomProducts(JSON.parse(localStorage.getItem("kassenspiel-products")||"[]"));setPriceOverrides(JSON.parse(localStorage.getItem("kassenspiel-price-overrides")||"{}"));setCoupons(JSON.parse(localStorage.getItem("kassenspiel-coupons")||"[]"));setStocks(JSON.parse(localStorage.getItem("kassenspiel-stocks")||"{}"));setCustomStores(JSON.parse(localStorage.getItem("kassenspiel-custom-stores")||"[]"));const saved=JSON.parse(localStorage.getItem("kassenspiel-settings")||"null");if(saved){setSettings(saved);setStoreDraft(saved.storeName);setLogoDraft(saved.logo)}const localReceipts=JSON.parse(localStorage.getItem("kassenspiel-receipts")||"[]");if(Array.isArray(localReceipts))setReceiptHistory(localReceipts);setSales(Number(localStorage.getItem("kassenspiel-sales")||0));setTransactions(Number(localStorage.getItem("kassenspiel-transactions")||0))}catch{}fetch("/api/receipts").then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(Array.isArray(data.receipts))setReceiptHistory(data.receipts)}).catch(()=>{});setHydrated(true);const tick=()=>setClock(new Date().toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"}));tick();const timer=setInterval(tick,30000);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(hydrated)localStorage.setItem("kassenspiel-products",JSON.stringify(customProducts))},[customProducts,hydrated]);
  useEffect(()=>{if(hydrated){localStorage.setItem("kassenspiel-price-overrides",JSON.stringify(priceOverrides));localStorage.setItem("kassenspiel-coupons",JSON.stringify(coupons))}},[priceOverrides,coupons,hydrated]);
  useEffect(()=>{if(hydrated){localStorage.setItem("kassenspiel-settings",JSON.stringify(settings));localStorage.setItem("kassenspiel-sales",String(sales));localStorage.setItem("kassenspiel-transactions",String(transactions))}},[settings,sales,transactions,hydrated]);
  useEffect(()=>{if(hydrated){localStorage.setItem("kassenspiel-stocks",JSON.stringify(stocks));localStorage.setItem("kassenspiel-custom-stores",JSON.stringify(customStores))}},[stocks,customStores,hydrated]);

  const baseProducts=[...defaultProducts.map(p=>({...p,storeType:"Supermarkt" as StoreType})),...shopProducts,...customProducts.map(p=>({...p,storeType:p.storeType||"Supermarkt" as StoreType}))];
  const allProducts=baseProducts.map(p=>({...p,price:priceOverrides[String(p.id)]??p.price,stock:stocks[String(p.id)]??p.stock??25}));
  const availableStoreOptions=[...storeOptions,...customStores];
  const products=allProducts.filter(p=>storeType==="Alle"||!storeType||p.storeType===storeType);
  const categories=Array.from(new Set(["Alle",...products.map(p=>p.category)]));
  const visibleProducts=useMemo(()=>products.filter(p=>{const q=search.trim().toLowerCase();return(category==="Alle"||p.category===category)&&(!q||p.name.toLowerCase().includes(q)||p.barcode.includes(q))}),[products,category,search]);
  const rawSubtotal=cart.reduce((s,i)=>s+i.price*i.quantity,0),subtotal=Math.max(0,rawSubtotal),tax=subtotal-subtotal/1.19,itemCount=cart.filter(i=>i.price>=0).reduce((s,i)=>s+i.quantity,0),typedPaymentTotal=Number(paymentAmount.replace(",",".")),payableTotal=Number.isFinite(typedPaymentTotal)&&typedPaymentTotal>0?typedPaymentTotal:subtotal,change=Math.max(0,Number(cash.replace(",",".")||0)-payableTotal);
  const printReceipts=printSelection.map(id=>receiptHistory.find(record=>record.id===id)).filter((record):record is Receipt=>!!record);
  const measureBase=measuringItem?measureData(measuringItem.baseUnit||measuringItem.unit):null,measureTarget=measureData(`1 ${measureUnit}`),measureValue=Number(measureAmount.replace(",",".")),measurePreview=measuringItem&&measureBase&&measureTarget&&measureBase.group===measureTarget.group&&Number.isFinite(measureValue)&&measureValue>0?Math.round(((measuringItem.basePrice??measuringItem.price)*(measureValue*measureTarget.factor)/(measureBase.amount*measureBase.factor))*100)/100:null;

  const login=(e:FormEvent)=>{e.preventDefault();if(username.trim().toLowerCase()==="admin"&&password==="1234"){setLoggedIn(true);setLoginError("")}else setLoginError("Benutzername oder Passwort ist falsch.")};
  const persistReceipt=(record:Receipt)=>{setReceiptHistory(current=>{const updated=[record,...current.filter(r=>r.id!==record.id)].sort((a,b)=>b.createdAt-a.createdAt);try{localStorage.setItem("kassenspiel-receipts",JSON.stringify(updated))}catch{}return updated});fetch("/api/receipts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(record)}).catch(()=>{})};
  const beep=()=>{try{const AudioContextClass=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext;const context=new AudioContextClass(),oscillator=context.createOscillator(),gain=context.createGain();oscillator.type="sine";oscillator.frequency.value=1050;gain.gain.setValueAtTime(.16,context.currentTime);gain.gain.exponentialRampToValueAtTime(.001,context.currentTime+.12);oscillator.connect(gain);gain.connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.12)}catch{}};
  const addProduct=(product:Product)=>{setCart(c=>{const found=c.find(i=>i.id===product.id);return found?c.map(i=>i.id===product.id?{...i,quantity:i.quantity+1}:i):[...c,{...product,quantity:1}]});setNotice(`${product.name} hinzugefügt`)};
  const openPayment=(method:"cash"|"card")=>{setPaymentAmount(subtotal.toFixed(2).replace(".",","));setCash("");setPaymentCouponCode("");setPaymentCoupon(null);setPaymentCouponError("");setPayment(method)};
  const openMeasure=(item:CartItem)=>{const baseUnit=item.baseUnit||item.unit,parsed=measureData(baseUnit);if(!parsed){setNotice("Für diesen Artikel ist keine Gewichts- oder Maßeinheit hinterlegt");return}setMeasuringItem(item);setMeasureAmount(item.measured?String(measureData(item.unit)?.amount||parsed.amount).replace(".",","):String(parsed.amount).replace(".",","));setMeasureUnit(item.measured?(measureData(item.unit)?.unit||parsed.unit):parsed.unit)};
  const saveMeasuredAmount=(e:FormEvent)=>{e.preventDefault();if(!measuringItem)return;const baseUnit=measuringItem.baseUnit||measuringItem.unit,base=measureData(baseUnit),wanted=Number(measureAmount.replace(",",".")),target=measureData(`1 ${measureUnit}`),basePrice=measuringItem.basePrice??measuringItem.price;if(!base||!target||base.group!==target.group||!Number.isFinite(wanted)||wanted<=0){setNotice("Bitte eine gültige Menge eingeben");return}const calculated=Math.round((basePrice*(wanted*target.factor)/(base.amount*base.factor))*100)/100,displayAmount=measureAmount.trim().replace(".",",");setCart(current=>current.map(item=>item.id===measuringItem.id?{...item,price:calculated,quantity:1,unit:`${displayAmount} ${measureUnit}`,basePrice,baseUnit,measured:true}:item));setMeasuringItem(null);setNotice(`${measuringItem.name}: ${displayAmount} ${measureUnit} = ${money(calculated)}`)};
  const applyCouponAtPayment=(coupon:Coupon)=>{const current=Number(paymentAmount.replace(",","."));if(!Number.isFinite(current)||current<=coupon.amount){setPaymentCouponError("Der Coupon ist höher als der aktuelle Zahlbetrag.");return false}setPaymentCoupon(coupon);setPaymentCouponCode(coupon.code);setPaymentAmount((Math.round((current-coupon.amount)*100)/100).toFixed(2).replace(".",","));setPaymentCouponError("");beep();setNotice(`Zeitungscoupon ${coupon.code}: ${money(coupon.amount)} abgezogen`);return true};
  const activatePaymentCoupon=()=>{setPaymentCouponError("");const code=paymentCouponCode.trim(),coupon=coupons.find(c=>c.active&&c.code.toLowerCase()===code.toLowerCase());if(!coupon){setPaymentCouponError("Dieser Zeitungscoupon ist nicht hinterlegt oder nicht aktiv.");return}applyCouponAtPayment(coupon)};
  const openPrintManager=(receiptId?:string)=>{setPrintSelection(receiptId?[receiptId]:[]);setShowPrintManager(true)};
  const togglePrintReceipt=(id:string)=>setPrintSelection(current=>{if(current.includes(id))return current.filter(value=>value!==id);if(current.length>=2){setNotice("Auf ein A4-Blatt passen höchstens zwei verschiedene Bons");return current}return[...current,id]});
  const applyCoupon=(coupon:Coupon)=>{setCart(current=>{const couponId=-coupon.id;if(current.some(item=>item.id===couponId)){setNotice(`Coupon ${coupon.code} wurde bereits benutzt`);return current}const discount:CartItem={id:couponId,name:`Coupon: ${coupon.label}`,price:-coupon.amount,category:"Angebot",icon:"🏷️",unit:`Code ${coupon.code}`,barcode:coupon.code,color:"#fff0cf",quantity:1,storeType:storeType||"Alle"};setNotice(`${coupon.label}: ${money(coupon.amount)} abgezogen`);return[...current,discount]})};
  const changeQuantity=(id:number,delta:number)=>setCart(c=>c.map(i=>i.id===id?{...i,quantity:i.quantity+delta}:i).filter(i=>i.quantity>0));
  const scan=()=>{if(!barcode.trim())return;scanLockRef.current=false;acceptScannedBarcode(barcode.trim(),"checkout")};
  const stopScanner=()=>{scannerControlsRef.current?.stop();scannerControlsRef.current=null;if(videoRef.current?.srcObject){(videoRef.current.srcObject as MediaStream).getTracks().forEach(track=>track.stop());videoRef.current.srcObject=null}setScannerMode(null);setScanSnapStatus("")};
  const acceptScannedBarcode=(value:string,mode:"checkout"|"mde"|"new"|"coupon")=>{if(scanLockRef.current)return;scanLockRef.current=true;const clean=value.trim();setBarcode("");beep();const coupon=coupons.find(c=>c.active&&c.code.toLowerCase()===clean.toLowerCase());if(mode==="coupon"){if(coupon)applyCouponAtPayment(coupon);else setPaymentCouponError("Dieser gescannte Zeitungscoupon ist nicht hinterlegt oder nicht aktiv.");stopScanner();return}const digitalReceipt=receiptHistory.find(r=>r.barcode===clean);if(digitalReceipt){stopScanner();setReceipt(digitalReceipt);setNotice(`Bon ${digitalReceipt.number} digital geöffnet`);return}if(coupon&&(mode==="checkout"||mode==="mde")){stopScanner();setNotice("Zeitungscoupons bitte erst im Bezahlfenster einlösen");return}if(mode==="new"){setNewProduct(p=>({...p,barcode:clean}));setProductError("");stopScanner();setShowProduct(true);setNotice("Barcode erkannt – jetzt Name und Preis eingeben");return}const found=products.find(p=>p.barcode===clean);if(found&&mode==="mde"){stopScanner();setMdeProduct(found);setNotice(`${found.name}: Preis und Lagerbestand geöffnet`)}else if(found){addProduct(found);stopScanner();setNotice(`${found.name} gescannt – Bip!`)}else{setNewProduct(p=>({...p,barcode:clean}));setProductError("");stopScanner();setShowProduct(true);setNotice("Neuer Barcode – bitte Produkt und Preis festlegen")}};
  const startScanner=(mode:"checkout"|"mde"|"new"|"coupon")=>{setScannerError("");setScanSnapStatus("");setBarcode("");scanLockRef.current=false;setScannerMode(mode)};
  useEffect(()=>{if(!scannerMode||!videoRef.current)return;let cancelled=false,nativeTimer=0,nativeBusy=false;const formats=[BarcodeFormat.EAN_13,BarcodeFormat.EAN_8,BarcodeFormat.UPC_A,BarcodeFormat.UPC_E,BarcodeFormat.CODE_128,BarcodeFormat.CODE_39,BarcodeFormat.ITF];const hints=new Map();hints.set(DecodeHintType.TRY_HARDER,true);hints.set(DecodeHintType.ALSO_INVERTED,true);hints.set(DecodeHintType.POSSIBLE_FORMATS,formats);const reader=new BrowserMultiFormatOneDReader(hints,{delayBetweenScanAttempts:8,delayBetweenScanSuccess:70});const NativeDetector=(window as typeof window&{BarcodeDetector?:NativeBarcodeDetectorConstructor}).BarcodeDetector;const detector=NativeDetector?new NativeDetector({formats:["ean_13","ean_8","upc_a","upc_e","code_128","code_39","itf"]}):null;const scanNative=async()=>{const video=videoRef.current;if(cancelled||nativeBusy||scanLockRef.current||!detector||!video||video.readyState<2)return;nativeBusy=true;try{const direct=await detector.detect(video);if(direct[0]?.rawValue){acceptScannedBarcode(direct[0].rawValue,scannerMode);return}for(const candidate of barcodeCandidates(video).slice(1,4)){const detected=await detector.detect(candidate);if(detected[0]?.rawValue){acceptScannedBarcode(detected[0].rawValue,scannerMode);return}}}catch{}finally{nativeBusy=false}};reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:60}}},videoRef.current,(result,_error,controls)=>{scannerControlsRef.current=controls;if(result&&!scanLockRef.current)acceptScannedBarcode(result.getText(),scannerMode)}).then(async controls=>{if(cancelled){controls.stop();return}scannerControlsRef.current=controls;const stream=videoRef.current?.srcObject as MediaStream|null;const track=stream?.getVideoTracks()[0];if(track){try{const capabilities=track.getCapabilities() as MediaTrackCapabilities&{zoom?:{min:number;max:number;step:number}};const advanced:Record<string,unknown>[]=[{focusMode:"continuous"},{exposureMode:"continuous"}];if(capabilities.zoom)advanced.push({zoom:Math.min(capabilities.zoom.max,Math.max(capabilities.zoom.min,1.25))});await track.applyConstraints({advanced:advanced as MediaTrackConstraintSet[]})}catch{}}nativeTimer=window.setInterval(scanNative,70);setScanSnapStatus(detector?"Mehrfach-Erkennung aktiv – Barcode wird automatisch gesucht …":"Barcode wird automatisch gesucht …")}).catch(()=>{if(!cancelled)setScannerError("Kamera konnte nicht gestartet werden. Bitte Kamerazugriff erlauben und die Seite neu öffnen.")});return()=>{cancelled=true;if(nativeTimer)window.clearInterval(nativeTimer);scannerControlsRef.current?.stop();scannerControlsRef.current=null}},[scannerMode]);
  const recognizeCurrentFrame=async()=>{const video=videoRef.current;if(!video||!scannerMode||video.readyState<2){setScanSnapStatus("Kamerabild ist noch nicht bereit.");return}setScanSnapStatus("Barcode wird gerade, gedreht und kontrastverstärkt geprüft …");const candidates=barcodeCandidates(video),NativeDetector=(window as typeof window&{BarcodeDetector?:NativeBarcodeDetectorConstructor}).BarcodeDetector;if(NativeDetector){try{const detector=new NativeDetector({formats:["ean_13","ean_8","upc_a","upc_e","code_128","code_39","itf"]});for(const candidate of candidates){const detected=await detector.detect(candidate);if(detected[0]?.rawValue){acceptScannedBarcode(detected[0].rawValue,scannerMode);return}}}catch{}}const hints=new Map();hints.set(DecodeHintType.TRY_HARDER,true);hints.set(DecodeHintType.ALSO_INVERTED,true);hints.set(DecodeHintType.POSSIBLE_FORMATS,[BarcodeFormat.EAN_13,BarcodeFormat.EAN_8,BarcodeFormat.UPC_A,BarcodeFormat.UPC_E,BarcodeFormat.CODE_128,BarcodeFormat.CODE_39,BarcodeFormat.ITF]);const stillReader=new BrowserMultiFormatOneDReader(hints);for(const candidate of candidates){try{const result=stillReader.decodeFromCanvas(candidate);acceptScannedBarcode(result.getText(),scannerMode);return}catch{}}setScanSnapStatus("Noch nicht erkannt: helle Spiegelung vermeiden und den Barcode kurz ruhig halten.")};
  const completePayment=()=>{const given=Number(cash.replace(",",".")||0),entered=Number(paymentAmount.replace(",","."));if(!cart.length)return;if(!Number.isFinite(entered)||entered<=0){setNotice("Bitte einen gültigen Zahlbetrag eingeben");return}const paymentTotal=Math.round(entered*100)/100;if(payment==="cash"&&given<paymentTotal){setNotice("Der gegebene Betrag ist zu klein");return}const now=Date.now(),number=String(now).slice(-8),couponAmount=paymentCoupon?.amount||0,manualBase=paymentTotal+couponAmount,manualDifference=Math.round((manualBase-subtotal)*100)/100;const receiptItems:CartItem[]=[...cart];if(Math.abs(manualDifference)>=.01)receiptItems.push({id:-now,name:manualDifference<0?"Preisnachlass an der Kasse":"Preisänderung an der Kasse",price:manualDifference,category:"Kassenbetrag",icon:manualDifference<0?"🏷️":"✎",unit:"Manuell eingegeben",barcode:`PRICE-${now}`,color:"#eef3f7",quantity:1,storeType:storeType||"Alle"});if(paymentCoupon)receiptItems.push({id:-now-1,name:`Coupon: ${paymentCoupon.label}`,price:-paymentCoupon.amount,category:"Angebot",icon:"🏷️",unit:`Code ${paymentCoupon.code}`,barcode:paymentCoupon.code,color:"#fff0cf",quantity:1,storeType:storeType||"Alle"});const paymentTax=paymentTotal-paymentTotal/1.19;const notes=[];if(Math.abs(manualDifference)>=.01)notes.push(`Zahlbetrag manuell von ${money(subtotal)} auf ${money(manualBase)} geändert.`);if(paymentCoupon)notes.push(`Coupon ${paymentCoupon.code}: ${money(paymentCoupon.amount)} Rabatt.`);const next:Receipt={id:crypto.randomUUID(),barcode:`9${now}`,items:receiptItems,total:paymentTotal,tax:paymentTax,payment:payment==="cash"?"Bar":"Karte",given:payment==="cash"?given:undefined,change:payment==="cash"?given-paymentTotal:undefined,date:new Date(now).toLocaleString("de-DE"),createdAt:now,number,kind:"sale",storeType:storeType||"Alle",note:notes.join(" ")||undefined};persistReceipt(next);setReceipt(next);setSales(v=>v+paymentTotal);setTransactions(v=>v+1);setStocks(current=>{const next={...current};cart.filter(item=>item.id>0).forEach(item=>{next[String(item.id)]=Math.max(0,(next[String(item.id)]??item.stock??25)-item.quantity)});return next});setCart([]);setPayment(null);setPaymentAmount("");setPaymentCoupon(null);setPaymentCouponCode("");setCash("");setNotice("Kauf, Preis und Coupon wurden gespeichert")};
  const createReturn=(original:Receipt)=>{const now=Date.now(),number=String(now).slice(-8);const returnedItems=original.items.map(item=>({...item,quantity:-Math.abs(item.quantity)}));const total=-Math.abs(original.total);const returned:Receipt={id:crypto.randomUUID(),barcode:`8${now}`,items:returnedItems,total,tax:-Math.abs(original.tax),payment:"Rückgabe",date:new Date(now).toLocaleString("de-DE"),createdAt:now,number,kind:"return",storeType:original.storeType,originalNumber:original.number,note:`Vollständige Rückgabe von Bon ${original.number}`};persistReceipt(returned);setSales(v=>Math.max(0,v+total));setTransactions(v=>v+1);setReceipt(returned);setNotice("Rückgabe verbucht – neuer Rückgabebon erstellt")};
  const saveEditedReceipt=()=>{if(!editingReceipt)return;const total=editingReceipt.items.reduce((sum,item)=>sum+item.price*item.quantity,0),tax=total-total/1.19;const updated={...editingReceipt,total,tax};persistReceipt(updated);setEditingReceipt(null);setReceipt(updated);setNotice("Bon wurde geändert und gespeichert")};
  const saveProductPrice=(e:FormEvent)=>{e.preventDefault();if(!editingProduct)return;const price=Number(editPrice.replace(",",".").replace(/[^0-9.]/g,""));if(!Number.isFinite(price)||price<=0){setNotice("Bitte einen gültigen Preis eingeben");return}setPriceOverrides(current=>({...current,[String(editingProduct.id)]:price}));setCart(current=>current.map(item=>item.id===editingProduct.id?{...item,price}:item));setEditingProduct(null);setNotice(`${editingProduct.name}: Preis auf ${money(price)} geändert`)};
  const createCoupon=(e:FormEvent)=>{e.preventDefault();setCouponError("");const code=couponDraft.code.trim(),label=couponDraft.label.trim()||"Angebot",amount=Number(couponDraft.amount.replace(",",".").replace(/[^0-9.]/g,""));if(!code){setCouponError("Bitte einen Coupon-Code eingeben oder scannen.");return}if(coupons.some(c=>c.code.toLowerCase()===code.toLowerCase())){setCouponError("Dieser Coupon-Code ist bereits vorhanden.");return}if(!Number.isFinite(amount)||amount<=0){setCouponError("Bitte einen gültigen Rabatt in Euro eingeben.");return}setCoupons(current=>[...current,{id:Date.now(),code,label,amount,active:true}]);setCouponDraft({code:"",label:"Angebot",amount:""});setNotice(`Coupon ${code} wurde gespeichert`)};
  const chooseAutomaticProductImage=async()=>{const name=newProduct.name.trim();if(!name){setProductError("Bitte zuerst den Artikelnamen eingeben, damit ein passendes Bild gefunden wird.");return}setProductError("");setAutoImageLoading(true);const image=await findProductImageByName(name,newProduct.category);setAutoImageLoading(false);if(!image){setProductError("Zu diesem Namen wurde kein passendes Bild gefunden. Du kannst ein Foto aufnehmen oder hochladen.");return}setNewProduct(current=>({...current,image}));setNotice(`Passendes Bild für ${name} gefunden`)};
  const createProduct=async(e:FormEvent)=>{e.preventDefault();setProductError("");const name=newProduct.name.trim(),barcodeValue=newProduct.barcode.trim(),price=Number(newProduct.price.replace(",",".").replace(/[^0-9.]/g,"")),amount=newProduct.amount.trim().replace(".",","),measure=newProduct.measure.trim();if(!name){setProductError("Bitte einen Artikelnamen eingeben.");return}if(!Number.isFinite(price)||price<=0){setProductError("Bitte einen gültigen Preis eingeben, zum Beispiel 1,49.");return}if(!amount||!/^\d+(?:[,.]\d+)?$/.test(amount)){setProductError("Bitte eine gültige Menge eingeben, zum Beispiel 500 oder 1,5.");return}if(!barcodeValue){setProductError("Bitte einen Barcode scannen oder eingeben.");return}if(allProducts.some(p=>p.barcode===barcodeValue)){setProductError("Dieser Barcode ist bereits bei einem anderen Artikel gespeichert.");return}let productImage=newProduct.image;if(!productImage){setAutoImageLoading(true);productImage=await findProductImageByName(name,newProduct.category);setAutoImageLoading(false)}const product:Product={id:Date.now(),name,price,unit:`${amount} ${measure||"Stück"}`,category:newProduct.category.trim()||"Eigene Artikel",barcode:barcodeValue,icon:newProduct.icon.trim()||"📦",color:"#e7f1ed",image:productImage||undefined,stock:Math.max(0,Number(newProduct.stock.replace(",","."))||0),storeType:storeType||"Alle"};const updated=[...customProducts,product];try{localStorage.setItem("kassenspiel-products",JSON.stringify(updated));setCustomProducts(updated)}catch{setProductError("Der Artikel konnte auf diesem Gerät nicht gespeichert werden. Bitte privaten Browsermodus ausschalten.");return}setNewProduct({name:"",price:"",amount:"1",measure:"Stück",category:"Eigene Artikel",barcode:"",icon:"📦",image:"",stock:"25"});setCategory("Eigene Artikel");setSearch("");setShowProduct(false);setNotice(`${name} wurde mit passendem Bild gespeichert`)};
  const loadProductImage=(file?:File)=>{if(!file)return;if(!file.type.startsWith("image/")){setProductError("Bitte ein Produktfoto als JPG, PNG oder HEIC auswählen.");return}setProductError("");const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=720,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext("2d");if(!ctx)return;ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);setNewProduct(p=>({...p,image:canvas.toDataURL("image/jpeg",.78)}))};img.onerror=()=>setProductError("Dieses Bild konnte nicht geladen werden. Bitte ein anderes Foto wählen.");img.src=String(reader.result)};reader.readAsDataURL(file)};
  const startProductCamera=async()=>{setPhotoCameraError("");try{if(!navigator.mediaDevices?.getUserMedia)throw new Error("camera");const stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:"environment"},width:{ideal:1920},height:{ideal:1080}}});productStreamRef.current=stream;setShowPhotoCamera(true)}catch{setPhotoCameraError("Die Kamera konnte nicht geöffnet werden. Bitte den Kamerazugriff im Browser erlauben.");setShowPhotoCamera(true)}};
  useEffect(()=>{if(showPhotoCamera&&productVideoRef.current&&productStreamRef.current){productVideoRef.current.srcObject=productStreamRef.current;void productVideoRef.current.play()}},[showPhotoCamera]);
  const stopProductCamera=()=>{productStreamRef.current?.getTracks().forEach(track=>track.stop());productStreamRef.current=null;if(productVideoRef.current)productVideoRef.current.srcObject=null;setShowPhotoCamera(false)};
  const captureProductPhoto=()=>{const video=productVideoRef.current;if(!video||video.readyState<2){setPhotoCameraError("Das Kamerabild ist noch nicht bereit.");return}const source=document.createElement("canvas");source.width=video.videoWidth;source.height=video.videoHeight;const sourceCtx=source.getContext("2d");if(!sourceCtx)return;sourceCtx.drawImage(video,0,0);const max=720,scale=Math.min(1,max/Math.max(source.width,source.height)),output=document.createElement("canvas");output.width=Math.round(source.width*scale);output.height=Math.round(source.height*scale);const outputCtx=output.getContext("2d");if(!outputCtx)return;outputCtx.drawImage(source,0,0,output.width,output.height);setNewProduct(p=>({...p,image:output.toDataURL("image/jpeg",.8)}));stopProductCamera();setNotice("Produktfoto aufgenommen")};
  useEffect(()=>()=>productStreamRef.current?.getTracks().forEach(track=>track.stop()),[]);
  const loadLogo=(file?:File)=>{if(!file)return;if(!file.type.startsWith("image/")){setNotice("Bitte eine Bilddatei auswählen");return}const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=600,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);const ctx=canvas.getContext("2d");if(!ctx)return;ctx.filter="grayscale(1) contrast(1.15)";ctx.drawImage(img,0,0,canvas.width,canvas.height);setLogoDraft(canvas.toDataURL("image/png"))};img.src=String(reader.result)};reader.readAsDataURL(file)};
  const saveSettings=()=>{setSettings({storeName:storeDraft.trim()||"Mein Laden",logo:logoDraft});setShowSettings(false);setNotice("Bon-Design wurde gespeichert")};
  const saveReceipt=()=>{if(!receipt)return;const logo=settings.logo?`<img src="${settings.logo}" style="display:block;max-width:150px;max-height:70px;margin:0 auto;filter:grayscale(1)">`:`<h2>${settings.storeName}</h2>`;const lines=receipt.items.map(i=>`<div><span>${i.quantity} × ${i.name}</span><b>${money(i.quantity*i.price)}</b></div>`).join("");const barcodeCanvas=document.querySelector(".receipt-preview-modal .receipt-barcode canvas") as HTMLCanvasElement|null;const barcodeImage=barcodeCanvas?.toDataURL("image/png")||"";const html=`<!doctype html><meta charset="utf-8"><title>Bon ${receipt.number}</title><style>body{width:72mm;margin:0 auto;padding:6mm 4mm;font:12px monospace;color:#000}header{text-align:center}div{display:flex;justify-content:space-between;margin:5px 0}hr{border:0;border-top:1px dashed #000}.total{font-size:16px}.barcode{display:block;width:100%;height:55px;object-fit:fill;margin:12px 0 2px}</style><header>${logo}<p>${receipt.kind==="return"?"RÜCKGABEBON":"KASSENBON"}</p></header><p>${receipt.date} · Bon ${receipt.number}</p><hr>${lines}<hr><div class="total"><b>SUMME</b><b>${money(receipt.total)}</b></div><div><span>Zahlung</span><span>${receipt.payment}</span></div><hr>${barcodeImage?`<img class="barcode" src="${barcodeImage}">`:""}<p style="text-align:center">${receipt.barcode}<br><br>Barcode scannen, um den Bon digital zu öffnen.</p>`;const url=URL.createObjectURL(new Blob([html],{type:"text/html;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`Kassenbon-${receipt.number}.html`;a.click();URL.revokeObjectURL(url);setNotice("Bon wurde gespeichert")};

  if(!loggedIn)return <main className="login-page"><section className="login-card"><div className="login-brand"><div className="brand-mark"><span/><span/><span/></div><div><strong>KASSENSPIEL</strong><small>Supermarkt-Kassensimulator</small></div></div><div className="login-copy"><span>GESCHÜTZTER KASSENBEREICH</span><h1>An der Kasse anmelden</h1><p>Melde dich mit deinem Kassenkonto an.</p></div><form onSubmit={login}><label>Benutzername<input autoFocus value={username} onChange={e=>setUsername(e.target.value)} placeholder="Benutzername"/></label><label>Passwort<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Passwort"/></label>{loginError&&<p className="login-error">{loginError}</p>}<button>Anmelden →</button></form><div className="demo-login"><span>Demo-Zugang</span><b>Benutzername: admin</b><b>Passwort: 1234</b></div></section></main>;

  if(!storeType)return <main className="store-select-page"><section className="store-select-card"><div className="login-brand"><div className="brand-mark"><span/><span/><span/></div><div><strong>KASSENSPIEL</strong><small>Wähle dein Geschäft</small></div></div><span className="modal-kicker">SPIEL STARTEN</span><h1>Welche Kasse möchtest du öffnen?</h1><p>Jeder Laden hat ein eigenes Sortiment. „Alle“ enthält alle Produkte gemeinsam.</p><div className="store-choice-grid">{availableStoreOptions.map(option=>{const count=option.type==="Alle"?allProducts.length:allProducts.filter(p=>p.storeType===option.type).length;return <button key={option.type} onClick={()=>{setStoreType(option.type);setCategory("Alle");setNotice(`${option.type} geöffnet`)}}><span>{option.icon}</span><strong>{option.type}</strong><small>{option.description}<br/><b>{count} Produkte</b></small></button>})}<button className="create-store-choice" onClick={()=>{const name=window.prompt("Wie soll der neue Laden heißen?","")?.trim();if(!name)return;if(availableStoreOptions.some(s=>s.type.toLowerCase()===name.toLowerCase())){setNotice("Diesen Laden gibt es bereits");return}const next={type:name,icon:"＋",description:"Eigener Laden · startet mit 0 Produkten"};setCustomStores(current=>[...current,next]);setStoreType(name);setCategory("Alle");setNotice(`${name} erstellt · 0 Produkte`)}}><span>＋</span><strong>Neuen Laden erstellen</strong><small>Eigener Laden · startet mit 0 Produkten</small></button></div><button className="store-logout" onClick={()=>setLoggedIn(false)}>Zurück zur Anmeldung</button></section></main>;

  return <main className="pos-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark"><span/><span/><span/></div><div><strong>KASSENSPIEL</strong><small>{storeType} · {settings.storeName}</small></div></div><div className="status-pill"><i/>{notice}</div><div className="header-actions"><button onClick={()=>setShowHistory(true)}>▤ Bons ({receiptHistory.length})</button><button onClick={()=>{setStoreDraft(settings.storeName);setLogoDraft(settings.logo);setShowSettings(true)}}>⚙ Bon & Laden</button><button onClick={()=>setStoreType(null)}>Laden wechseln</button><button onClick={()=>{setLoggedIn(false);setStoreType(null)}}>Abmelden</button></div></header>
    <section className="dashboard-strip"><div><span className="metric-icon green">↗</span><p><small>Tagesumsatz</small><strong>{money(sales)}</strong></p></div><div><span className="metric-icon blue">▤</span><p><small>Vorgänge heute</small><strong>{transactions}</strong></p></div><div><span className="metric-icon orange">◷</span><p><small>Aktuelle Uhrzeit</small><strong>{clock}</strong></p></div><div className="dashboard-actions"><button onClick={()=>setShowHistory(true)}>▤ Käufe & Bons</button><button className="coupon-button" onClick={()=>setShowCoupons(true)}>🏷 Angebote & Coupons</button><button className="camera-product-button" onClick={()=>startScanner("new")}>▣ Barcode für Artikel</button><button className="new-product-button" onClick={()=>setShowProduct(true)}>＋ Neuer Artikel</button><button onClick={()=>{setSales(0);setTransactions(0);setNotice("Neuer Kassentag gestartet")}}>↻ Neuer Kassentag</button></div></section>
    <div className="workspace"><section className="catalog-panel"><div className="scan-row"><label className="search-box"><span>⌕</span><input aria-label="Produkte suchen" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Produkt suchen …"/></label><div className="barcode-controls"><label className="barcode-box"><span>▥</span><input aria-label="Barcode oder Coupon eingeben" value={barcode} onChange={e=>setBarcode(e.target.value)} onKeyDown={e=>e.key==="Enter"&&scan()} placeholder="Barcode oder Coupon-Code"/><button onClick={scan}>Eingeben</button></label><button className="camera-scan-button" onClick={()=>startScanner("mde")} aria-label="MDE Barcode mit Kamera scannen">▣ MDE-SCAN</button></div></div><nav className="categories">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</nav><div className="product-header"><h1>Produkte</h1><span>{visibleProducts.length} Artikel</span><button onClick={()=>setShowProduct(true)}>＋ Artikel erstellen</button></div><div className="product-grid">{visibleProducts.map(p=><button className="product-card" key={p.id} onClick={()=>addProduct(p)}><span className="product-visual" style={{background:p.color}}><span className="product-fallback" aria-hidden="true">{p.icon}</span>{p.image&&<img src={p.image} alt="" onError={e=>{e.currentTarget.style.display="none"}}/>}</span><span className="product-copy"><strong>{p.name}</strong><small>{p.unit} · #{p.barcode}</small><b>{money(p.price)}</b><em className={(p.stock||0)>0?"stock-ok":"stock-out"}>{(p.stock||0)>0?`${p.stock} verfügbar`:"Nicht verfügbar"}</em></span><span className="edit-product-price" role="button" tabIndex={0} title="Preis ändern" onClick={e=>{e.stopPropagation();setEditingProduct(p);setEditPrice(String(p.price).replace(".",","))}} onKeyDown={e=>{if(e.key==="Enter"){e.stopPropagation();setEditingProduct(p);setEditPrice(String(p.price).replace(".",","))}}}>✎</span><span className="add">+</span></button>)}{!visibleProducts.length&&<div className="empty-products">Kein Produkt gefunden.</div>}</div></section>
      <aside className="cart-panel"><div className="cart-title"><div><h2>Aktueller Einkauf</h2><span>{itemCount} Artikel</span></div>{cart.length>0&&<button onClick={()=>setCart([])}>Leeren</button>}</div><div className="cart-list">{cart.length===0?<div className="empty-cart"><div>🛒</div><h3>Noch keine Artikel</h3><p>Wähle links ein Produkt oder gib einen Barcode ein.</p></div>:cart.map(i=><div className="cart-item" key={i.id}><span className="cart-icon" style={{background:i.color}}><span aria-hidden="true">{i.icon}</span>{i.image&&<img src={i.image} alt="" onError={e=>{e.currentTarget.style.display="none"}}/>}</span><div className="cart-name"><strong>{i.name}</strong><small>{money(i.price)} / {i.unit}</small>{measureData(i.baseUnit||i.unit)&&<button className="measure-item-button" onClick={()=>openMeasure(i)}>⚖ Menge/Gewicht eingeben</button>}</div><div className="quantity"><button onClick={()=>changeQuantity(i.id,-1)}>−</button><b>{i.quantity}</b><button onClick={()=>changeQuantity(i.id,1)}>+</button></div><strong className="line-total">{money(i.price*i.quantity)}</strong></div>)}</div><div className="checkout"><div className="summary"><p><span>Zwischensumme</span><strong>{money(subtotal)}</strong></p><p><span>Enthaltene MwSt. (19 %)</span><span>{money(tax)}</span></p></div><div className="grand-total"><span>Gesamt</span><strong>{money(subtotal)}</strong></div><button className="pay-button" disabled={!cart.length} onClick={()=>openPayment("card")}><span>▣</span> Mit Karte zahlen</button><button className="cash-button" disabled={!cart.length} onClick={()=>openPayment("cash")}><span>€</span> Bar bezahlen</button></div></aside></div>

    <nav className="mobile-pos-dock" aria-label="Mobile Kassenbedienung"><button onClick={()=>startScanner("mde")}><span>▥</span><b>Scannen</b></button><button onClick={()=>document.querySelector(".cart-panel")?.scrollIntoView({behavior:"smooth"})}><span>🛒</span><b>Warenkorb</b><em>{cart.reduce((sum,item)=>sum+item.quantity,0)}</em></button><button className="mobile-pay" disabled={!cart.length} onClick={()=>openPayment("card")}><span>€</span><b>Bezahlen</b></button></nav>

    {payment&&<div className="modal-backdrop"><div className="payment-modal"><button className="modal-close" onClick={()=>{setPayment(null);setPaymentAmount("");setPaymentCoupon(null);setPaymentCouponCode("");setCash("")}}>×</button><div className={`payment-symbol ${payment}`}>{payment==="card"?"▣":"€"}</div><p className="eyebrow">{payment==="card"?"Kartenzahlung":"Barzahlung"}</p><div className="payment-total-entry"><label>Zu zahlender Betrag</label><div><input autoFocus inputMode="decimal" value={paymentAmount} onChange={e=>{setPaymentAmount(e.target.value);setPaymentCoupon(null);setPaymentCouponError("")}} placeholder="0,00"/><span>€</span></div><small>Warenkorb ursprünglich: {money(subtotal)} · Betrag kann geändert werden</small></div><div className={`payment-coupon-entry ${paymentCoupon?"applied":""}`}><label>Zeitungscoupon des Kunden einlösen</label><div><input value={paymentCouponCode} onChange={e=>setPaymentCouponCode(e.target.value)} placeholder="Gedruckten Coupon-Code eingeben" disabled={!!paymentCoupon}/><button onClick={activatePaymentCoupon} disabled={!!paymentCoupon||!paymentCouponCode.trim()}>{paymentCoupon?"✓ Eingelöst":"Einlösen"}</button></div><button className="scan-newspaper-coupon" onClick={()=>startScanner("coupon")} disabled={!!paymentCoupon}>▣ Barcode auf dem Zeitungscoupon scannen</button>{paymentCoupon?<small>− {money(paymentCoupon.amount)} · {paymentCoupon.label}</small>:paymentCouponError&&<small className="error">{paymentCouponError}</small>}</div><h2>{money(payableTotal)}</h2>{payment==="card"?<div className="terminal"><span className="waves">)))</span><strong>{money(payableTotal)} – Karte auflegen</strong><small>Simulation – keine echte Zahlung</small></div>:<div className="cash-entry"><label>Vom Kunden gegeben<input inputMode="decimal" value={cash} onChange={e=>setCash(e.target.value)} placeholder="0,00"/><span>€</span></label><div><span>Rückgeld</span><strong>{money(change)}</strong></div><div className="quick-cash">{[5,10,20,50].map(a=><button onClick={()=>setCash(String(a))} key={a}>{a} €</button>)}</div></div>}<button className="complete-button" onClick={completePayment}>Zahlung abschließen & Bon ansehen</button></div></div>}

    {measuringItem&&<div className="modal-backdrop measure-backdrop"><form className="form-modal measure-modal" onSubmit={saveMeasuredAmount}><button type="button" className="modal-close" onClick={()=>setMeasuringItem(null)}>×</button><span className="modal-kicker">WAAGE / MENGENEINGABE</span><h2>{measuringItem.name}</h2><p>Grundpreis: {money(measuringItem.basePrice??measuringItem.price)} für {measuringItem.baseUnit||measuringItem.unit}. Gib die tatsächlich gekaufte Menge ein.</p><div className="measure-step">1. Gewicht oder Menge eintippen</div><div className="measure-input-row"><label>Menge<input autoFocus inputMode="decimal" value={measureAmount} onChange={e=>setMeasureAmount(e.target.value)} placeholder="z. B. 1,5"/></label><label>Einheit<select value={measureUnit} onChange={e=>setMeasureUnit(e.target.value)}>{measureUnits(measureData(measuringItem.baseUnit||measuringItem.unit)?.group).map(unit=><option key={unit}>{unit}</option>)}</select></label></div><div className="measure-live-total"><span>Automatisch berechneter Preis</span><strong>{measurePreview===null?"–":money(measurePreview)}</strong></div><div className="measure-example">Beispiel: Tomaten 500 g für 2,49 € → 1,5 kg kostet automatisch 7,47 €.</div><button className="save-form" disabled={measurePreview===null}>2. Menge übernehmen & Preis speichern</button></form></div>}

    {scannerMode&&<div className="modal-backdrop scanner-backdrop"><section className="scanner-modal"><button className="modal-close" onClick={stopScanner}>×</button><span className="modal-kicker">AUTOMATISCHER BLITZSCANNER</span><h2>{scannerMode==="coupon"?"Zeitungscoupon scannen":scannerMode==="mde"?"MDE-Produktabfrage":scannerMode==="checkout"?"Produkt scannen":"Barcode für neuen Artikel"}</h2><p>{scannerMode==="coupon"?"Halte den gedruckten Barcode des Kunden in den Rahmen. Der Rabatt wird automatisch übernommen.":scannerMode==="mde"?"Barcode nur in den grünen Rahmen halten. Preis und Lagerbestand erscheinen sofort – ohne Knopfdruck.":scannerMode==="checkout"?"Halte den Produktbarcode ruhig in den grünen Rahmen. Nach dem Bip landet der Artikel im Warenkorb.":"Halte den Barcode in den Rahmen. Danach kannst du Name und Preis festlegen."}</p><div className="camera-view"><video ref={videoRef} playsInline muted/><div className="scan-frame"><i/><i/><i/><i/><span/></div><small>⚡ Automatik aktiv · Barcode vollständig in den Rahmen</small></div>{scannerError&&<p className="scanner-error">{scannerError}</p>}{scanSnapStatus&&<p className="scan-snap-status">{scanSnapStatus}</p>}<div className="scan-help">Kein Knopf nötig: Kamera und zweite Erkennung prüfen fortlaufend jeden Barcode.</div><div className="manual-scan"><label>Oder Code manuell eingeben<input value={barcode} onChange={e=>setBarcode(e.target.value)} placeholder={scannerMode==="coupon"?"Code vom Zeitungscoupon":"Barcode-Nummer"}/></label><button disabled={!barcode.trim()} onClick={()=>acceptScannedBarcode(barcode.trim(),scannerMode)}>Übernehmen & Bip</button></div></section></div>}

    {mdeProduct&&<div className="modal-backdrop mde-product-backdrop"><section className="mde-product-modal"><button className="modal-close" onClick={()=>setMdeProduct(null)}>×</button><span className="modal-kicker">MDE · PRODUKT GEFUNDEN</span><div className="mde-product-head"><div className="mde-product-image" style={{background:mdeProduct.color}}>{mdeProduct.image?<img src={mdeProduct.image} alt={mdeProduct.name}/>:mdeProduct.icon}</div><div><h2>{mdeProduct.name}</h2><strong>{money(mdeProduct.price)}</strong><small>Barcode {mdeProduct.barcode}</small></div></div><div className="mde-product-facts"><p><span>Lagerbestand</span><b>{mdeProduct.stock||0} {mdeProduct.unit}</b></p><p><span>Verfügbarkeit</span><b className={(mdeProduct.stock||0)>0?"available":"unavailable"}>{(mdeProduct.stock||0)>0?"Sofort verfügbar":"Nicht verfügbar"}</b></p><p><span>Kategorie</span><b>{mdeProduct.category}</b></p><p><span>Laden</span><b>{storeType}</b></p></div><div className="mde-product-actions"><button onClick={()=>{setMdeProduct(null);startScanner("mde")}}>▣ Nächstes Produkt</button><button className="primary" disabled={(mdeProduct.stock||0)<=0} onClick={()=>{addProduct(mdeProduct);setMdeProduct(null);setNotice(`${mdeProduct.name} zum Kunden-Einkauf hinzugefügt`)}}>＋ Zum Einkauf</button><button className="pay" disabled={!cart.length} onClick={()=>{setMdeProduct(null);openPayment("card")}}>€ Jetzt bezahlen</button></div></section></div>}

    {editingProduct&&<div className="modal-backdrop price-edit-backdrop"><form className="form-modal price-edit-modal" onSubmit={saveProductPrice}><button type="button" className="modal-close" onClick={()=>setEditingProduct(null)}>×</button><span className="modal-kicker">PREIS ÄNDERN</span><h2>{editingProduct.name}</h2><p>Alter Preis: <strong>{money(editingProduct.price)}</strong>. Gib den neuen Verkaufspreis ein.</p><label className="settings-name">Neuer Preis in €<input autoFocus inputMode="decimal" value={editPrice} onChange={e=>setEditPrice(e.target.value)} placeholder="z. B. 79,99"/></label><button className="save-form">Neuen Preis speichern</button></form></div>}

    {showCoupons&&<div className="modal-backdrop coupon-backdrop"><section className="coupon-modal"><button className="modal-close" onClick={()=>{setShowCoupons(false);setCouponError("")}}>×</button><span className="modal-kicker">ANGEBOTE & COUPONS</span><h2>Rabatt-Code erstellen</h2><p>Der Code kann eingetippt oder als Barcode gescannt werden. Der Rabatt wird einmal vom Einkauf abgezogen.</p><form className="coupon-form" onSubmit={createCoupon}><label>Coupon-Code<input value={couponDraft.code} onChange={e=>setCouponDraft({...couponDraft,code:e.target.value})} placeholder="z. B. ANGEBOT5"/></label><label>Name des Angebots<input value={couponDraft.label} onChange={e=>setCouponDraft({...couponDraft,label:e.target.value})} placeholder="Sommer-Angebot"/></label><label>Rabatt in €<input inputMode="decimal" value={couponDraft.amount} onChange={e=>setCouponDraft({...couponDraft,amount:e.target.value})} placeholder="5,00"/></label>{couponError&&<p className="product-form-error">{couponError}</p>}<button className="save-form">Coupon speichern</button></form><div className="coupon-list">{coupons.length===0?<p>Noch keine Coupons erstellt.</p>:coupons.map(c=><article key={c.id}><span>🏷️</span><div><strong>{c.label}</strong><small>Code: {c.code}</small></div><b>− {money(c.amount)}</b><button onClick={()=>setCoupons(current=>current.map(item=>item.id===c.id?{...item,active:!item.active}:item))}>{c.active?"Aktiv":"Aus"}</button><button className="coupon-delete" onClick={()=>setCoupons(current=>current.filter(item=>item.id!==c.id))}>Löschen</button></article>)}</div></section></div>}

    {showProduct&&<div className="modal-backdrop"><form className="form-modal" onSubmit={createProduct}><button type="button" className="modal-close" onClick={()=>{setShowProduct(false);setProductError("");stopProductCamera()}}>×</button><span className="modal-kicker">ARTIKELVERWALTUNG</span><h2>Neuen Artikel erstellen</h2><p>Ohne eigenes Foto sucht die Kasse beim Speichern automatisch ein passendes Bild zum Artikelnamen.</p><div className="product-photo-field">{newProduct.image?<div className="product-photo-preview"><img src={newProduct.image} alt="Neues Produkt"/><button type="button" onClick={()=>setNewProduct({...newProduct,image:""})}>Bild entfernen</button></div>:<div className="product-photo-actions"><label>↥ Bild hochladen<input type="file" accept="image/*" onChange={e=>loadProductImage(e.target.files?.[0])}/></label><button type="button" onClick={startProductCamera}>◉ Kamera öffnen & Foto machen</button><button type="button" className="auto-product-image" disabled={autoImageLoading} onClick={chooseAutomaticProductImage}>{autoImageLoading?"Bild wird gesucht …":"✨ Passendes Bild automatisch suchen"}</button></div>}</div><div className="form-grid"><label className="wide">Artikelname<input autoFocus value={newProduct.name} onChange={e=>setNewProduct({...newProduct,name:e.target.value})} placeholder="z. B. Ayran"/></label><label>Preis in €<input inputMode="decimal" value={newProduct.price} onChange={e=>setNewProduct({...newProduct,price:e.target.value})} placeholder="1,49"/></label><label>Menge<input inputMode="decimal" value={newProduct.amount} onChange={e=>setNewProduct({...newProduct,amount:e.target.value})} placeholder="z. B. 500"/></label><label>Maßeinheit<select value={newProduct.measure} onChange={e=>setNewProduct({...newProduct,measure:e.target.value})}><option>Stück</option><option>Liter</option><option value="L">L</option><option>ml</option><option>kg</option><option>g</option><option>m</option><option>cm</option><option>mm</option><option>Packung</option><option>Karton</option><option>Set</option></select></label><label>Barcode<input inputMode="numeric" value={newProduct.barcode} onChange={e=>setNewProduct({...newProduct,barcode:e.target.value})} placeholder="500001"/></label><label>Symbol (falls kein Bild)<input value={newProduct.icon} onChange={e=>setNewProduct({...newProduct,icon:e.target.value})} placeholder="📦"/></label><label>Lagerbestand<input inputMode="numeric" value={newProduct.stock} onChange={e=>setNewProduct({...newProduct,stock:e.target.value})} placeholder="25"/></label><label className="wide">Kategorie<input value={newProduct.category} onChange={e=>setNewProduct({...newProduct,category:e.target.value})} placeholder="Eigene Artikel"/></label></div>{productError&&<p className="product-form-error" role="alert">{productError}</p>}<button type="submit" className="save-form" disabled={autoImageLoading}>{autoImageLoading?"Passendes Bild wird gesucht …":"Artikel jetzt speichern"}</button></form></div>}

    {showPhotoCamera&&<div className="modal-backdrop product-camera-backdrop"><section className="product-camera-modal"><button className="modal-close" onClick={stopProductCamera}>×</button><span className="modal-kicker">PRODUKTFOTO</span><h2>Produkt fotografieren</h2><p>Halte das Produkt mittig vor die Kamera und drücke den Auslöser.</p>{photoCameraError?<p className="scanner-error">{photoCameraError}</p>:<div className="product-camera-view"><video ref={productVideoRef} playsInline muted/><div className="photo-guide"/></div>}<div className="product-camera-actions"><button type="button" className="secondary" onClick={stopProductCamera}>Abbrechen</button><button type="button" className="shutter-button" disabled={!!photoCameraError} onClick={captureProductPhoto}><span/> Foto aufnehmen</button></div></section></div>}

    {showSettings&&<div className="modal-backdrop"><section className="form-modal settings-modal"><button className="modal-close" onClick={()=>setShowSettings(false)}>×</button><span className="modal-kicker">BON-DESIGN</span><h2>Laden & Logo einrichten</h2><p>Das Logo wird automatisch schwarz-weiß und mittig auf dem Bon platziert.</p><label className="settings-name">Ladenname<input value={storeDraft} onChange={e=>setStoreDraft(e.target.value)} placeholder="Mein Laden"/></label><label className="logo-upload"><input type="file" accept="image/*" onChange={e=>loadLogo(e.target.files?.[0])}/>{logoDraft?<img src={logoDraft} alt="Logo-Vorschau"/>:<><span>⬆</span><strong>Logo hochladen</strong><small>PNG oder JPG auswählen</small></>}</label>{logoDraft&&<button className="remove-logo" onClick={()=>setLogoDraft("")}>Logo entfernen – Ladenname verwenden</button>}<button className="save-form" onClick={saveSettings}>Bon-Design speichern</button></section></div>}

    {showHistory&&<div className="modal-backdrop history-backdrop"><section className="history-modal"><div className="history-head"><div><span className="modal-kicker">KAUFARCHIV</span><h2>Alle Käufe und Bons</h2><p>Mit Datum und Uhrzeit gespeichert. Jeder Bon kann erneut geöffnet, geändert oder gedruckt werden.</p></div><div className="history-head-actions"><button onClick={()=>openPrintManager()}>▤ Bons zum Drucken auswählen</button><button onClick={()=>setShowHistory(false)}>×</button></div></div><div className="history-list">{receiptHistory.length===0?<div className="history-empty">Noch keine Käufe gespeichert.</div>:receiptHistory.map(record=><article key={record.id} className={record.kind==="return"?"return-record":""}><div className="history-type"><span>{record.kind==="return"?"↩":"✓"}</span><div><strong>{record.kind==="return"?"Rückgabe":"Verkauf"} · Bon {record.number}</strong><small>{record.date} · {record.storeType}</small></div></div><div className="history-total">{money(record.total)}</div><div className="history-actions"><button onClick={()=>{setReceipt(record);setShowHistory(false)}}>Bon ansehen</button><button onClick={()=>openPrintManager(record.id)}>Drucken</button><button onClick={()=>setEditingReceipt(structuredClone(record))}>Verändern</button>{record.kind==="sale"&&<button className="return-button" onClick={()=>{createReturn(record);setShowHistory(false)}}>Rückgabe</button>}</div></article>)}</div></section></div>}

    {showPrintManager&&<div className="modal-backdrop print-manager-backdrop"><section className="print-manager-modal"><button className="modal-close" onClick={()=>setShowPrintManager(false)}>×</button><span className="modal-kicker">A4 DRUCKAUSWAHL</span><h2>Welche Bons möchtest du drucken?</h2><p>Wähle einen Bon oder zwei unterschiedliche Bons. Es wird nichts doppelt gedruckt.</p><div className="print-choice-count"><strong>{printSelection.length}</strong><span>von maximal 2 Bons ausgewählt</span></div><div className="print-choice-list">{receiptHistory.length===0?<p>Noch keine Bons vorhanden.</p>:receiptHistory.map(record=><label key={record.id} className={printSelection.includes(record.id)?"selected":""}><input type="checkbox" checked={printSelection.includes(record.id)} onChange={()=>togglePrintReceipt(record.id)}/><span>{record.kind==="return"?"↩":"▤"}</span><div><strong>Bon {record.number}</strong><small>{record.date} · {record.kind==="return"?"Rückgabe":"Verkauf"}</small></div><b>{money(record.total)}</b></label>)}</div><div className="print-manager-actions"><button className="secondary" onClick={()=>setShowPrintManager(false)}>Abbrechen</button><button className="primary" disabled={!printReceipts.length} onClick={()=>window.print()}>{printReceipts.length===1?"1 Bon drucken":"2 verschiedene Bons auf A4 drucken"}</button></div></section></div>}

    {editingReceipt&&<div className="modal-backdrop edit-receipt-backdrop"><section className="edit-receipt-modal"><button className="modal-close" onClick={()=>setEditingReceipt(null)}>×</button><span className="modal-kicker">BON BEARBEITEN</span><h2>Bon {editingReceipt.number} verändern</h2><p>Artikelname, Menge, Preis und Notiz können geändert werden. Die Summe wird neu berechnet.</p><div className="edit-lines">{editingReceipt.items.map((item,index)=><div key={`${item.id}-${index}`}><input aria-label="Artikelname" value={item.name} onChange={e=>setEditingReceipt({...editingReceipt,items:editingReceipt.items.map((line,i)=>i===index?{...line,name:e.target.value}:line)})}/><input aria-label="Menge" type="number" value={item.quantity} onChange={e=>setEditingReceipt({...editingReceipt,items:editingReceipt.items.map((line,i)=>i===index?{...line,quantity:Number(e.target.value)}:line)})}/><label><input aria-label="Preis" inputMode="decimal" value={String(item.price)} onChange={e=>setEditingReceipt({...editingReceipt,items:editingReceipt.items.map((line,i)=>i===index?{...line,price:Number(e.target.value.replace(",","."))||0}:line)})}/><span>€</span></label></div>)}</div><label className="receipt-note-edit">Notiz<textarea value={editingReceipt.note||""} onChange={e=>setEditingReceipt({...editingReceipt,note:e.target.value})} placeholder="Optionale Notiz zum Bon"/></label><div className="edit-receipt-total"><span>Neue Summe</span><strong>{money(editingReceipt.items.reduce((sum,item)=>sum+item.price*item.quantity,0))}</strong></div><button className="save-form" onClick={saveEditedReceipt}>Änderungen speichern</button></section></div>}

    {receipt&&<div className="modal-backdrop receipt-backdrop"><section className="receipt-preview-modal"><div className="receipt-preview-head"><div><span>{receipt.kind==="return"?"↩ RÜCKGABE GESPEICHERT":"✓ BON DIGITAL GEÖFFNET"}</span><h2>{receipt.kind==="return"?"Rückgabebon":"Bon kontrollieren"}</h2><p>Der Barcode öffnet diesen Bon später jederzeit wieder.</p></div><button onClick={()=>setReceipt(null)}>×</button></div><div className="receipt-stage"><ReceiptPaper receipt={receipt} settings={settings}/></div><div className="receipt-actions"><button className="secondary" onClick={()=>setReceipt(null)}>Schließen</button><button className="secondary" onClick={()=>setEditingReceipt(structuredClone(receipt))}>✎ Verändern</button>{receipt.kind==="sale"&&<button className="secondary return-action" onClick={()=>createReturn(receipt)}>↩ Rückgabe</button>}<button className="secondary" onClick={saveReceipt}>⇩ Speichern</button><button className="primary" onClick={()=>openPrintManager(receipt.id)}>▤ Druckauswahl öffnen</button></div></section></div>}
    {printReceipts.length>0&&<div className={`print-sheet count-${printReceipts.length}`}>{printReceipts.map(record=><ReceiptPaper key={record.id} receipt={record} settings={settings} className="print-receipt"/>)}</div>}
  </main>
}
